### ISSUE TITLE
Playground does not work for whisper

### ISSUE THREAD

**Issue by rrbanda** [containers/podman-desktop-extension-ai-lab#1013]
<img width="1512" alt="Screenshot 2024-04-28 at 11 30 55 AM" src="https://github.com/containers/podman-desktop-extension-ai-lab/assets/93591339/94473b16-6eac-40ab-b1eb-c0389e81975e">

**Comment by cdrage** [comment]
> <img alt="Screenshot 2024-04-28 at 11 30 55 AM" width="1512" src="https://private-user-images.githubusercontent.com/93591339/326269208-94473b16-6eac-40ab-b1eb-c0389e81975e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNTY1MzksIm5iZiI6MTcxNDM1NjIzOSwicGF0aCI6Ii85MzU5MTMzOS8zMjYyNjkyMDgtOTQ0NzNiMTYtNmVhYy00MGFiLWIxZWItYzAzODllODE5NzVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDAyMDM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyNmUxMzQwNTBjNjMwMTZlNTExYmM5ODAwMmFkNGU5MzE2ZWEwMjQ1YmIyMGY5OTliNWU2ZjdlMTgxNTZmZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.N-__Jy4BLRhv9sLCTqp3RsooQXSmjqa7zooLtEqf2SE">

You can see on the top right that it says "Model Serivce not running" 

I have a feeling the Whisper gguf is not working anymore?

If I go to the pod controlling the ai lab, I get this error:

```
gguf_init_from_file: invalid magic characters 'lmgg'
llama_model_load: error loading model: llama_model_loader: failed to load model from /models/ggml-small.bin

llama_load_model_from_file: failed to load model
Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib64/python3.9/site-packages/llama_cpp/server/__main__.py", line 88, in <module>
    main()
  File "/usr/local/lib64/python3.9/site-packages/llama_cpp/server/__main__.py", line 74, in main
    app = create_app(
  File "/usr/local/lib64/python3.9/site-packages/llama_cpp/server/app.py", line 138, in create_app
    set_llama_proxy(model_settings=model_settings)
  File "/usr/local/lib64/python3.9/site-packages/llama_cpp/server/app.py", line 75, in set_llama_proxy
    _llama_proxy = LlamaProxy(models=model_settings)
  File "/usr/local/lib64/python3.9/site-packages/llama_cpp/server/model.py", line 31, in __init__
    self._current_model = self.load_llama_from_model_settings(
  File "/usr/local/lib64/python3.9/site-packages/llama_cpp/server/model.py", line 138, in load_llama_from_model_settings
    _model = create_fn(
  File "/usr/local/lib64/python3.9/site-packages/llama_cpp/llama.py", line 314, in __init__
    self._model = _LlamaModel(
  File "/usr/local/lib64/python3.9/site-packages/llama_cpp/_internals.py", line 55, in __init__
    raise ValueError(f"Failed to load model from file: {path_model}")
ValueError: Failed to load model from file: /models/ggml-small.bin
gguf_init_from_file: invalid magic characters 'lmgg'
llama_model_load: error loading model: llama_model_loader: failed to load model from /models/ggml-small.bin

llama_load_model_from_file: failed to load model
Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib64/python3.9/site-packages/llama_cpp/server/__main__.py", line 88, in <module>
    main()
  File "/usr/local/lib64/python3.9/site-packages/llama_cpp/server/__main__.py", line 74, in main
    app = create_app(
  File "/usr/local/lib64/python3.9/site-packages/llama_cpp/server/app.py", line 138, in create_app
    set_llama_proxy(model_settings=model_settings)
  File "/usr/local/lib64/python3.9/site-packages/llama_cpp/server/app.py", line 75, in set_llama_proxy
    _llama_proxy = LlamaProxy(models=model_settings)
  File "/usr/local/lib64/python3.9/site-packages/llama_cpp/server/model.py", line 31, in __init__
    self._current_model = self.load_llama_from_model_settings(
  File "/usr/local/lib64/python3.9/site-packages/llama_cpp/server/model.py", line 138, in load_llama_from_model_settings
    _model = create_fn(
  File "/usr/local/lib64/python3.9/site-packages/llama_cpp/llama.py", line 314, in __init__
    self._model = _LlamaModel(
  File "/usr/local/lib64/python3.9/site-packages/llama_cpp/_internals.py", line 55, in __init__
    raise ValueError(f"Failed to load model from file: {path_model}")
ValueError: Failed to load model from file: /models/ggml-small.bin
gguf_init_from_file: invalid magic characters 'lmgg'
llama_model_load: error loading model: llama_model_loader: failed to load model from /models/ggml-small.bin

llama_load_model_from_file: failed to load model
Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib64/python3.9/site-packages/llama_cpp/server/__main__.py", line 88, in <module>
    main()
  File "/usr/local/lib64/python3.9/site-packages/llama_cpp/server/__main__.py", line 74, in main
    app = create_app(
  File "/usr/local/lib64/python3.9/site-packages/llama_cpp/server/app.py", line 138, in create_app
    set_llama_proxy(model_settings=model_settings)
  File "/usr/local/lib64/python3.9/site-packages/llama_cpp/server/app.py", line 75, in set_llama_proxy
    _llama_proxy = LlamaProxy(models=model_settings)
  File "/usr/local/lib64/python3.9/site-packages/llama_cpp/server/model.py", line 31, in __init__
    self._current_model = self.load_llama_from_model_settings(
  File "/usr/local/lib64/python3.9/site-packages/llama_cpp/server/model.py", line 138, in load_llama_from_model_settings
    _model = create_fn(
  File "/usr/local/lib64/python3.9/site-packages/llama_cpp/llama.py", line 314, in __init__
    self._model = _LlamaModel(
  File "/usr/local/lib64/python3.9/site-packages/llama_cpp/_internals.py", line 55, in __init__
    raise ValueError(f"Failed to load model from file: {path_model}")
ValueError: Failed to load model from file: /models/ggml-small.bin

```

**Comment by axel7083** [comment]
The playground should not be able to start with the whisper model. 

Closing in favour of https://github.com/containers/podman-desktop-extension-ai-lab/issues/1181
