### ISSUE TITLE
Cannot Install Podman AI Lab Extension on Podman Desktop via Flatpak on Fedora Linux Konoite

### ISSUE THREAD

**Issue by denyshorman** [containers/podman-desktop-extension-ai-lab#1277]
### Bug description

The attempt to install Podman AI Lab Extension using Podman Desktop fails with the following error: 

```bash
Error: Cannot find extension for /var/home/denys/.local/share/containers/podman-desktop/plugins/ghcriocontainerspodmandesktopextensionailab/dist
Stack trace:
Error: Cannot find extension for /var/home/denys/.local/share/containers/podman-desktop/plugins/ghcriocontainerspodmandesktopextensionailab/dist
    at _module._load (/app/main/resources/app.asar/packages/main/dist/index.cjs:146:33696)
    at Module.require (node:internal/modules/cjs/loader:1242:19)
    at require (node:internal/modules/helpers:176:18)
    at Module.<anonymous> (/var/home/denys/.local/share/containers/podman-desktop/plugins/ghcriocontainerspodmandesktopextensionailab/dist/extension.js:5:26)
    at Module._compile (node:internal/modules/cjs/loader:1391:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1451:10)
    at Module.load (node:internal/modules/cjs/loader:1214:32)
    at Module._load (node:internal/modules/cjs/loader:1030:12)
    at c._load (node:electron/js2c/node_init:2:13672)
    at _module._load (/app/main/resources/app.asar/packages/main/dist/index.cjs:146:33447)
```

### Operating system

Fedora Linux 40.20240621.0 (Kinoite)

### Installation Method

from Podman-Desktop extension page

### Version

1.0.0

### Steps to reproduce

1. Install Fedora Kinoite
2. Install Podman Desktop using Flatpak
3. Install Podman AI Lab Extension using Podman Desktop

### Additional context

System Information
 - OS: Fedora Linux 40.20240621.0 (Kinoite)
 - Podman Desktop Installation Method: **Flatpak**
 - Podman Desktop Version: 1.10.2
 - Podman Version: 5.1.1
 - Podman AI Lab Extension Version: 1.1.2

**Comment by jeffmaury** [comment]
Fixed by https://github.com/containers/podman-desktop/commit/ff0eba5a96276028202b836ea369247bb916b558
