### ISSUE TITLE
Error when pulling ChatBot recipe using GPU support with LibKrun on Mac: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string 

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop-extension-ai-lab#1548]
### Bug description

Error when pulling ChatBot recipe using GPU support with LibKrun on Mac: `TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TyperArray, or DataView. Received undefined.`

![Screenshot_20240815_114145](https://github.com/user-attachments/assets/fecbe785-d054-4bc9-8e8f-2938f914665b)

### Operating system

Mac OS 14 M2

### Installation Method

from `ghcr.io/containers/podman-desktop-extension-ai-lab` container image

### Version

next (development version)

### Steps to reproduce

1. on Mac OS 14 M2
2. Install podman desktop 1.12.0
3. Install 1.2.0 AI Lab extension
4. Create Podman Machine with Libkrun provider
5. Enable GPU Support (I tried even without GPU support, no difference)
6. Go To recipe Catalog
7. Choose chatBot (Also tried summarizer)
8. Start the app
9. Assert: Application is started
Actual result: an error mentioned above.

### Relevant log output
```
VM5:2 main ↪️ [ai-lab] There is no workers compatible. Using default local mounting
console.<computed> @ VM5:2
(anonymous) @ VM5:2
emit @ VM4 sandbox_bundle:2
onMessage @ VM4 sandbox_bundle:2
VM5:2 main ↪️ [ai-lab] There is no workers compatible. Using default local mounting
console.<computed> @ VM5:2
(anonymous) @ VM5:2
emit @ VM4 sandbox_bundle:2
onMessage @ VM4 sandbox_bundle:2
VM5:2 main ↪️ [ai-lab] Something went wrong while trying to get image inspect TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Hash.update (node:internal/crypto/hash:115:11)
    at Lie.getImageHash (/Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:135:17395)
    at Lie.pullImage (/Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:135:17326)
    at Object.pullImage (/Applications/Podman Desktop.app/Contents/Resources/app.asar/packages/main/dist/index.cjs:151:55304)
    at getImageInfo (/Users/podmanqe/.local/share/containers/podman-desktop/plugins/ghcriocontainerspodmandesktopextensionailab/dist/extension.js:2517:46)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async LlamaCppPython.perform (/Users/podmanqe/.local/share/containers/podman-desktop/plugins/ghcriocontainerspodmandesktopextensionailab/dist/extension.js:3301:23)
    at async InferenceManager.createInferenceServer (/Users/podmanqe/.local/share/containers/podman-desktop/plugins/ghcriocontainerspodmandesktopextensionailab/dist/extension.js:30593:29)
    at async RecipeManager.buildRecipe (/Users/podmanqe/.local/share/containers/podman-desktop/plugins/ghcriocontainerspodmandesktopextensionailab/dist/extension.js:416020:40)
    at async ApplicationManager.initApplication (/Users/podmanqe/.local/share/containers/podman-desktop/plugins/ghcriocontainerspodmandesktopextensionailab/dist/extension.js:3446:30)
console.<computed> @ VM5:2
(anonymous) @ VM5:2
emit @ VM4 sandbox_bundle:2
onMessage @ VM4 sandbox_bundle:2

```

**Comment by ScrewTSW** [comment]
Reproduced on AppleHV
