### ISSUE TITLE
Missing package manager version in e2e-main.yaml

### ISSUE THREAD

**Issue by danivilla9** [containers/podman-desktop-extension-ai-lab#1692]
### Bug description

There is a missing package manager version in this workflow and it's throwing an error:
```
  Please specify it by one of the following ways:
    - in the GitHub Action config with the key "version"
    - in the package.json with the key "packageManager"
      at readTarget (/home/runner/work/_actions/pnpm/action-setup/v4/dist/index.js:1:5186)
      at runSelfInstaller (/home/runner/work/_actions/pnpm/action-setup/v4/dist/index.js:1:3742)
      at async install (/home/runner/work/_actions/pnpm/action-setup/v4/dist/index.js:1:2[9](https://github.com/containers/podman-desktop-extension-ai-lab/actions/runs/10789282246/job/29921930114#step:5:10)76)
      at async main (/home/runner/work/_actions/pnpm/action-setup/v4/dist/index.js:1:444)
  Error: Error: No pnpm version is specified.
  Please specify it by one of the following ways:
    - in the GitHub Action config with the key "version"
    - in the package.json with the key "packageManager"
```

### Operating system

Linux Fedora

### Installation Method

None

### Version

next (development version)

**Comment by benoitf** [comment]
looks like there is still an issue
