### ISSUE TITLE
Build of the Model image fails from Flatpak Install

### ISSUE THREAD

**Issue by feloy** [containers/podman-desktop-extension-ai-lab#392]
When building the model image for chatbot from Podman Desktop UI (executed from flatpak):

```
STEP 5/7: RUN pip install --no-cache-dir --upgrade -r /locallm/requirements.txt
Collecting llama-cpp-python (from -r /locallm/requirements.txt (line 1))
  Downloading llama_cpp_python-0.2.44.tar.gz (36.6 MB)
     ━━━━━━━                                  6.5/36.6 MB 610.5 kB/s eta 0:00:50
ERROR: Exception:
                 Traceback (most recent call last):
                                                     File "/opt/app-root/lib64/python3.9/site-packages/pip/_vendor/urllib3/response.py", line 438, in _error_catcher
                                                              yield
                                                                     File "/opt/app-root/lib64/python3.9/site-packages/pip/_vendor/urllib3/response.py", line 561, in read
                                                                    data = self._fp_read(amt) if not fp_closed else b""
               File "/opt/app-root/lib64/python3.9/site-packages/pip/_vendor/urllib3/response.py", line 527, in _fp_read
                  return self._fp.read(amt) if amt is not None else self._fp.read()
                                                                                     File "/usr/lib64/python3.9/http/client.py", line 463, in read
                                            n = self.readinto(b)
                                                                  File "/usr/lib64/python3.9/http/client.py", line 507, in readinto
                             n = self.fp.readinto(b)
                                                      File "/usr/lib64/python3.9/socket.py", line 704, in readinto
            return self._sock.recv_into(b)
                                            File "/usr/lib64/python3.9/ssl.py", line 1275, in recv_into
                                                                                                           return self.read(nbytes, buffer)
                                   File "/usr/lib64/python3.9/ssl.py", line 1133, in read
                                                                                             return self._sslobj.read(len, buffer)
                        socket.timeout: The read operation timed out
                                                                    During handling of the above exception, another exception occurred:
                             Traceback (most recent call last):
                                                                 File "/opt/app-root/lib64/python3.9/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
                                                                                 status = run_func(*args)
                                                                                                           File "/opt/app-root/lib64/python3.9/site-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
                                                                                                             return func(self, options, args)
                                     File "/opt/app-root/lib64/python3.9/site-packages/pip/_internal/commands/install.py", line 377, in run
                                     requirement_set = resolver.resolve(
                                                                          File "/opt/app-root/lib64/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve
                                                                                           result = self._result = resolver.resolve(
                            File "/opt/app-root/lib64/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
                                  state = resolution.resolve(requirements, max_rounds=max_rounds)
                                                                                                   File "/opt/app-root/lib64/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 397, in resolve
                                                                                                         self._add_to_criteria(self.state.criteria, r, parent=None)
                                                           File "/opt/app-root/lib64/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _add_to_criteria
                                                                          if not criterion.candidates:
                                                                                                        File "/opt/app-root/lib64/python3.9/site-packages/pip/_vendor/resolvelib/structs.py", line 156, in __bool__
                                                                                                             return bool(self._sequence)
                                File "/opt/app-root/lib64/python3.9/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
                                                           return any(self)
                                                                             File "/opt/app-root/lib64/python3.9/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
                                                                                                         return (c for c in iterator if id(c) not in self._incompatible_ids)
                                                                    File "/opt/app-root/lib64/python3.9/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
                                                                                                 candidate = func()
           File "/opt/app-root/lib64/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 182, in _make_candidate_from_link
                                              base: Optional[BaseCandidate] = self._make_base_candidate_from_link(
          File "/opt/app-root/lib64/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 228, in _make_base_candidate_from_link
                                                  self._link_candidate_cache[link] = LinkCandidate(
                                                                                                     File "/opt/app-root/lib64/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 290, in __init__
                super().__init__(
                                   File "/opt/app-root/lib64/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
                                                        self.dist = self._prepare()
                                                                                     File "/opt/app-root/lib64/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 222, in _prepare
                                                                                                          dist = self._prepare_distribution()
                                     File "/opt/app-root/lib64/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 301, in _prepare_distribution
                                                                       return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
                                           File "/opt/app-root/lib64/python3.9/site-packages/pip/_internal/operations/prepare.py", line 525, in prepare_linked_requirement
                                                                    return self._prepare_linked_requirement(req, parallel_builds)
                         File "/opt/app-root/lib64/python3.9/site-packages/pip/_internal/operations/prepare.py", line 596, in _prepare_linked_requirement
                                                   local_file = unpack_url(
                                                                             File "/opt/app-root/lib64/python3.9/site-packages/pip/_internal/operations/prepare.py", line 168, in unpack_url
                                                                                      file = get_http_url(
                                                                                                           File "/opt/app-root/lib64/python3.9/site-packages/pip/_internal/operations/prepare.py", line 109, in get_http_url
            from_path, content_type = download(link, temp_dir.path)
                                                                     File "/opt/app-root/lib64/python3.9/site-packages/pip/_internal/network/download.py", line 147, in __call__
                                                                          for chunk in chunks:
                                                                                                File "/opt/app-root/lib64/python3.9/site-packages/pip/_internal/cli/progress_bars.py", line 53, in _rich_progress_bar
     for chunk in iterable:
                             File "/opt/app-root/lib64/python3.9/site-packages/pip/_internal/network/utils.py", line 63, in response_chunks
                                     for chunk in response.raw.stream(
                                                                        File "/opt/app-root/lib64/python3.9/site-packages/pip/_vendor/urllib3/response.py", line 622, in stream
                                                                         data = self.read(amt=amt, decode_content=decode_content)
                         File "/opt/app-root/lib64/python3.9/site-packages/pip/_vendor/urllib3/response.py", line 587, in read
                        raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
                                                                                          File "/usr/lib64/python3.9/contextlib.py", line 137, in __exit__
                                                    self.gen.throw(typ, value, traceback)
                                                                                           File "/opt/app-root/lib64/python3.9/site-packages/pip/_vendor/urllib3/response.py", line 443, in _error_catcher
                                                                                                    raise ReadTimeoutError(self._pool, None, "Read timed out.")
                                                     pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='[files.pythonhosted.org](http://files.pythonhosted.org/)', port=443): Read timed out.
Error:building at STEP "RUN pip install --no-cache-dir --upgrade -r /locallm/requirements.txt": while running runtime: exit status 2
```

**Comment by jeffmaury** [comment]
Looks like an HTTP error can you build an image that install packages

**Comment by feloy** [comment]
It is reproducible only on DV's machine for now

**Comment by jeffmaury** [comment]
> It is reproducible only on DV's machine for now

DV's network connection is known worldwide for not being reliable :)

**Comment by feloy** [comment]
But the build passes when it runs the build from the podman cli `podman build ...`

**Comment by veillard** [comment]
Okay I just tested with Podman Desktop 1.9.1 installed on Fedora 39 with Flatpak, used the latest tag 
ghcr.io/containers/podman-desktop-extension-ai-lab:nightly

Cicking on Chatbot, Start AI App, the checkout of the repository actually worked this time

But indeed Building llamacpp-server turns red after a bit of time, error:
"Something went wrong while building the image: building at STEP "RUN pip install --no-cache-dir --upgrade -r /locallm/requirements.txt": while running runtime: exit status 2"

**Comment by jeffmaury** [comment]
Closing as it's related to timeout
