### ISSUE TITLE
bug(recipe): deletion fail because of undefined Status value

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop-extension-ai-lab#746]
https://github.com/containers/podman-desktop-extension-ai-lab/assets/42176370/8b33782a-2427-4ca5-9588-849b1b97898d

```
11:43:55 [main] [ai-lab] error getting pods statuses TypeError: Cannot read properties of undefined (reading 'Status')
    at C:\Users\axels\Documents\github\redhat\studio-extension\packages\backend\dist\extension.js:4060:137
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async ApplicationManager.checkPodsHealth (C:\Users\axels\Documents\github\redhat\studio-extension\packages\backend\dist\extension.js:4058:31)
```

cc @feloy might be related ?

**Comment by axel7083** [comment]
Okey the problem was because I selected a model which was not the one recommanded, leave the page, came back, and the stop button was here even tho the key (recipe-id - model-id) was not the right one selected, and making (maybe?) it trying to delete something that does not exist ?
